-- =====================================================
-- COMPLETE FIX FOR TEACHER REGISTRATION ISSUES
-- =====================================================
-- This fixes both problems:
-- 1. Admin can't see teachers (missing staff records)
-- 2. Teacher sees "No class assigned" (missing assignments)
-- =====================================================

-- Step 1: Create missing staff records for teachers
-- This links teachers created in Settings to the staff table so admin can see them
INSERT INTO staff (
  id,
  staff_number,
  full_name,
  email,
  position,
  specialization,
  employment_date,
  status,
  school_id
)
SELECT 
  au.id,
  NULL, -- Will be auto-generated by trigger
  COALESCE(au.raw_user_meta_data->>'full_name', 'Teacher'),
  au.email,
  'Teacher',
  COALESCE(au.raw_user_meta_data->>'specialization', 'General'),
  au.created_at::date,
  'active',
  u.school_id
FROM auth.users au
LEFT JOIN users u ON au.id = u.id
WHERE au.raw_user_meta_data->>'role' = 'teacher'
  AND NOT EXISTS (
    SELECT 1 FROM staff s WHERE s.id = au.id
  )
  AND u.school_id IS NOT NULL
ON CONFLICT (id) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  email = EXCLUDED.email,
  position = EXCLUDED.position,
  status = 'active';

-- Step 2: Ensure users table has all teacher records
INSERT INTO users (
  id,
  email,
  role,
  full_name,
  school_id
)
SELECT 
  au.id,
  au.email,
  'teacher',
  COALESCE(au.raw_user_meta_data->>'full_name', 'Teacher'),
  -- Get school_id from admin users (assuming single school setup)
  (SELECT school_id FROM users WHERE role = 'admin' LIMIT 1)
FROM auth.users au
WHERE au.raw_user_meta_data->>'role' = 'teacher'
  AND NOT EXISTS (
    SELECT 1 FROM users u WHERE u.id = au.id
  )
ON CONFLICT (id) DO UPDATE SET
  role = 'teacher',
  full_name = EXCLUDED.full_name;

-- Step 3: Create teacher_class_assignments table if it doesn't exist
CREATE TABLE IF NOT EXISTS teacher_class_assignments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  teacher_id UUID REFERENCES users(id) ON DELETE CASCADE,
  class_name TEXT NOT NULL,
  subject TEXT,
  school_id UUID REFERENCES schools(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Step 4: Enable RLS on teacher_class_assignments
ALTER TABLE teacher_class_assignments ENABLE ROW LEVEL SECURITY;

-- Step 5: Create RLS policies for teacher_class_assignments
DROP POLICY IF EXISTS "Users can view their school's teacher assignments" ON teacher_class_assignments;
CREATE POLICY "Users can view their school's teacher assignments" ON teacher_class_assignments
  FOR SELECT USING (
    school_id IN (
      SELECT school_id FROM users WHERE id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Admins can manage teacher assignments" ON teacher_class_assignments;
CREATE POLICY "Admins can manage teacher assignments" ON teacher_class_assignments
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid() 
      AND role = 'admin' 
      AND school_id = teacher_class_assignments.school_id
    )
  );

-- Step 6: Assign teachers to default classes (so they don't see "No class assigned")
-- This creates a basic assignment for each teacher
INSERT INTO teacher_class_assignments (
  teacher_id,
  class_name,
  subject,
  school_id
)
SELECT 
  u.id,
  'Primary 1', -- Default class assignment
  'General', -- Default subject
  u.school_id
FROM users u
WHERE u.role = 'teacher'
  AND u.school_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM teacher_class_assignments tca 
    WHERE tca.teacher_id = u.id
  )
ON CONFLICT DO NOTHING;

-- Step 7: Verification - Show what we've created
SELECT 
  'TEACHERS IN STAFF TABLE (What admin sees):' as info,
  s.staff_number,
  s.full_name,
  s.email,
  s.position,
  s.status,
  sc.school_name
FROM staff s
LEFT JOIN schools sc ON s.school_id = sc.id
WHERE s.position LIKE '%eacher%'
ORDER BY s.full_name;

SELECT 
  'TEACHER CLASS ASSIGNMENTS (What teachers see):' as info,
  u.email as teacher_email,
  u.full_name as teacher_name,
  tca.class_name,
  tca.subject,
  sc.school_name
FROM teacher_class_assignments tca
JOIN users u ON tca.teacher_id = u.id
LEFT JOIN schools sc ON tca.school_id = sc.id
ORDER BY u.full_name;

-- Step 8: Show summary
SELECT 
  'TEACHER REGISTRATION FIX COMPLETE!' as status,
  COUNT(DISTINCT s.id) as teachers_in_staff_table,
  COUNT(DISTINCT tca.teacher_id) as teachers_with_class_assignments
FROM staff s
LEFT JOIN teacher_class_assignments tca ON s.id = tca.teacher_id
WHERE s.position LIKE '%eacher%';

-- =====================================================
-- INSTRUCTIONS FOR ADMIN:
-- =====================================================
-- 
-- After running this script:
-- 
-- 1. ADMIN VIEW:
--    - Go to Settings → Teachers
--    - You should now see all teachers listed
--    - You can assign them to specific classes
-- 
-- 2. TEACHER VIEW:
--    - Teachers can now login successfully
--    - They will see "Primary 1 - General" as default assignment
--    - Admin can change this to specific classes/subjects
-- 
-- 3. TO ASSIGN SPECIFIC CLASSES:
--    - Use the teacher management interface
--    - Or run SQL to update teacher_class_assignments table
-- 
-- =====================================================